server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
    enableSelfPreservation: false

#zuul:
#  prefix: /api
#  routes:
#    base:
#      path: /base/**
#      serviceId: base-service

#ribbon:
#  eureka:
#    enabled: true